name: PR Request Release Note

permissions:
  contents: read

on:
  pull_request:
    types:
      - closed

jobs:
  request-release-note:
    if: >-
      github.repository_owner == 'llvm' &&
      startsWith(github.ref, 'refs/heads/release')

    runs-on: ubuntu-latest
    steps:
      # We need to pull the script from the main branch, so that we ensure
      # we get the latest version of this script.
      - name: Checkout Scripts
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
        with:
          sparse-checkout: |
            llvm/utils/git/requirements.txt
            llvm/utils/git/github-automation.py
          sparse-checkout-cone-mode: false

      - name: Install Dependencies
        run: |
          pip install --require-hashes -r llvm/utils/git/requirements.txt

      - name: Request Release Note
        env:
          # We need to use an llvmbot token here, because we are mentioning a user.
          GITHUB_TOKEN: ${{ github.token }}
        run: |
          python3 llvm/utils/git/github-automation.py \
            --repo "$GITHUB_REPOSITORY" \
            --token "$GITHUB_TOKEN" \
            request-release-note \
            --pr-number ${{ github.event.pull_request.number}}

      - uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f #v6.0.0
        if: always()
        with:
          name: workflow-args
          path: |
            comments
